if (CMAKE_SYSTEM_NAME MATCHES "Windows")
   message(FATAL_ERROR "Please build it on Linux environment!")
elseif (CMAKE_SYSTEM_NAME MATCHES "Windows")
   message(FATAL_ERROR "Please build it on Linux environment!")
endif()
