#!/bin/bash
set -e

if ps -ef | grep proot
then
    killall -9 proot
fi

if ps -ef | grep chroot
then
    echo please kill all chroot containers to continue. && exit 127
else
    echo no chroot container running！
fi

test -d /usr/etc/ && rm -rf -v /usr/etc
test -d /usr/tmp && rm -rf -v /usr/tmp
test -d /usr/var && rm -rf -v /usr/var
test -d /usr/home && rm -rf -v /usr/home
