#!/bin/bash
set -e

if ps -ef | grep chroot
then
echo please kill all chroot containers to continue. && exit 127
else
echo no chroot container running！
fi

test -d /usr/etc/container | rm -rf -v
test -d /usr/tmp | rm -rf -v
test -d /usr/etc/var | rm -rf -v
test -f /usr/bin/container-console | rm -rf -v

