#!/bin/bash

# shellcheck disable=SC2086,SC2154,SC2155,SC2046,SC2001,SC2063,SC2009
set -e

if ps -ef | grep proot; then
  killall -9 proot
fi

if ps -ef | grep chroot; then
  if bash src/share/ruri_stop.sh && src/share/ruri_remove.sh; then
    echo ruri stop successfully.
  else
    echo please kill all chroot containers to continue. && exit 127
  fi
else
  echo no chroot container running！
fi

test -d /usr/etc/ && rm -rf -v /usr/etc
test -d /usr/tmp && rm -rf -v /usr/tmp
test -d /usr/var && rm -rf -v /usr/var
test -d /usr/home && rm -rf -v /usr/home
